title: Welcome to my website
description: Eric Giunchi (eric.giunchi2@unibo.it), Postdoc researcher at DIFA-University of Bologna, Bologna, Italy.
logo: assets/img/myself.jpeg

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
